# Site settings
title: Shawna Mattison - Software Developer
description: Shawna Mattison - Software Developer
url: "http://www.shawnamattison.com"

# User settings
username: Shawna Mattison
user_title: Software Developer
email: shawnamatt@gmail.com
github_username:  shawndromat
linkedin_username: shawnamattison

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
